module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URLs: 'http://139.59.76.223/anytimedoc/api/',
  BASE_URL: 'http://139.59.76.223/halo/api/',
    home :'home',
    Signin :'Signin',
    Signup :'Signup',
    guid:'',
    muid:'',
    module:'',
    prod :[],
    quantity:'',
    diagnostic :[],
    addid:[],
    mid:'',
    addid:'',
    sele :'',
    categoryId:'',
    brandId:'',
    youtubekey:'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    voip:'',
    currentAddress:[],
    pharacy:[],
    firebaseToken:'',
    mera:'0',
    like:0,
    is_yt:0,
    tagName:'',
    ismember:0,
    counter:'0',
    newsWhich:'',
    low:0,
    high:0,
    appply : 0,
    onlinetype:'',
    department:'',
    newsImage:'',
    newsTitle:'',
    front_main :'front_main',
    industry :'',
    categoryID : '',
    coupan:'',
    coupanid:'',
    array :[],
    userID:'',
    profile :'',
    delivery:'',
    location:'Current Location',
    currLoc:'',
    locationliketogo:'Where would you like to go?',
    doctor_condition:'online',
    token: '',
    mybookingid:'',
    productname : '',
    username: '',
    gender: '',
    email: '',
    password: '',
    otps: '',
    nurse :'',
    lab:[],
    labid:'',
    bookingflag:'',
    bookingid:'',
    another:'',
    anothername:'',
    bookingstatus:'',
    chatstatus:'',
    nurseArray:[],
    serviceid :'',
    dob: '',
    lat:'28.737324',
    long:'77.090981',
    lats:'',
    longs:'',
    appointmentArray :[],
    appointment_details:'',
    speciality :'',
    surgries:[],
    emergency_number:'',
    illness:[],
    allergies:[],
    selectedAddress:[],
    date:'',
    time:'',
    packageId:'',
    equipmentfor:'',
    user_details:'',
    equipment:[],
    sidq:'',
    artdesc:'',
    labdetail:[],
    type:'',
    problem:'',
    searchSpeciality:'',
    medicalEquipment:[],
    shipTime:'',
    imagePath:'',
    mystatus:'Offline',
    related:'',
    productid: '',
    cartId :'',
    myid :'',
    video:'',
    newsid :'',
    derive_category :'derive_category',
    derive_detail_category : 'derive_detail_category',
    info_number :'',
    info_email : '',
    mainid : '',
    user_id:'34',
    comment:[],
    dervie_detail_of_product : 'dervie_detail_of_product',
    userInfo :[],
    internet:"It seems your internet connectivity is low.Please connect your internet",
    myname :'',
    mymobile :'',
      YOUTUBE_API : 'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    mymember:[],
    price:'',
    referal :'',
    apply_to:'',
    groupName :'',
    groupId :'',
    groupImage:'',
    profileImage:'',
    editGroup:'',
    myemail :'',
    myusername:'',
    mymobile :'',
    is_refer_verify:'',
   referral_code :'',
    referral:'',
    rentPurchase:'',
    nurseDetail:[],
    mypassword :'',
    mydeviceID :'',
    mydeviceType :'',
    mydeviceToken :'',
    mymodel_name :'',
    mycarrier_name :'',
    mydevice_country :'',
    mydevice_memory :'',
    otps :'',
    fmobile :'',
    isScreen :'',
    isScreen :'',
    keyword:'',
    author_id :'',
    author :'',
    another:'',
    comment_id:'',
    post_id:'',
    wallets:'',
    regular:'Nunito-Regular',
    bold:'Nunito-Bold',
    semi:'Nunito-SemiBold',
    anotherUsername:'',
    commentFlagId:'',
    need_help:'need_help',
    onlinename:'',
    onlinegender:'',
    onlinedob:'',
    onlineaddress:'',
    onlinearea:'',
    onlinecity:'',
    onlineMember:[],
    hid:'',
    bookingtype:'',
    mytypes:'',
    listofimages:"",
    hids:'',
    anotherid:'',
    forgetEmail :'',
    ytr:'',
    amount:'',
    discount:'',
    total:'',

    COLOR: {
        Header:'#910000',
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',

    },
};
